version: "3.9"
services: 
    db:
        image: postgres
        #container_name: postgres
        environment: 
            - POSTGRES_DB=apicidade
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes: 
            - apicidade_data:/var/lib/postgres

volumes: 
    apicidade_data:
